name: Ghidra
on: push
jobs:
  # swy: 64-bit linux build --
  build-lnx:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install dependencies
      run: |
        java -version
        # swy: get rid of this repo once gradle 5.0 is properly supported on ubuntu :)
        sudo add-apt-repository ppa:cwchien/gradle
        sudo apt-get update
        sudo apt install gradle flex bison

    - name: Restore the cached downloads for things Ghidra depends on
      uses: actions/cache@v2
      with:
        path: build/downloads
        key: ghidra

    - name: Build Ghidra
      run: |
        gradle --init-script gradle/support/fetchDependencies.gradle init
        gradle buildGhidra
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Linux
        path: build/dist/
        if-no-files-found: error

  # swy: 64-bit windows build --
  build-win:
    name: Windows
    runs-on: windows-latest
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install dependencies
      run: |
        java -version
        choco install winflexbison
        cd $env:ProgramData\chocolatey\lib\winflexbison\tools
        ls
        Copy-Item win_flex.exe flex.exe
        Copy-Item win_bison.exe bison.exe
        ls
        echo "$env:ProgramData\chocolatey\lib\winflexbison\tools" >> $GITHUB_PATH

    - name: Restore the cached downloads for things Ghidra depends on
      uses: actions/cache@v2
      with:
        path: build/downloads
        key: ghidra

    - name: Build Ghidra
      run: |
        gradle --init-script gradle/support/fetchDependencies.gradle init
        gradle buildGhidra
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Windows
        path: build\dist\
        if-no-files-found: error
 
  # swy: 64-bit macos build --
  build-mac:
    name: macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install dependencies
      env:
        HOMEBREW_ANALYTICS_OFF: 1
      run: |
        java -version
        brew install gradle flex bison

    - name: Restore the cached downloads for things Ghidra depends on
      uses: actions/cache@v2
      with:
        path: build/downloads
        key: ghidra

    - name: Build Ghidra
      run: |
        gradle --init-script gradle/support/fetchDependencies.gradle init
        gradle buildGhidra
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: macOS
        path: build/dist/
        if-no-files-found: error
